import { Component, ViewChild } from '@angular/core';
import { StorageService, User } from '../../services/storage.service';
import { Platform, AlertController, ToastController, IonList } from '@ionic/angular';

@Component({
  selector: 'app-profile',
  templateUrl: './profile.page.html',
  styleUrls: ['./profile.page.scss'],
})

export class ProfilePage {

  users: User[] = [];
  oldUser: User = <User>{};
  username: any;
  email;
  image: any;
  int: number;

  bookCompleted = false;
  bookCompletedV1 = false;
  bookCompleted2 = false;
  bookCompleted3 = false;
  bookCompleted4 = false;
  bookCompleted5 = false;
  bookCompleted6 = false;
  bookCompleted7 = false;
  bookCompleted8 = false;
  bookCompleted9 = false;
  bookCompleted10 = false;
  bookCompleted11 = false;
  bookCompleted12 = false;
  bookCompleted13 = false;
  bookCompleted14 = false;
  bookCompleted15 = false;
  bookCompleted16 = false;
  bookCompleted17 = false;
  bookCompleted18 = false;
  bookCompleted19 = false;
  bookCompleted20 = false;
  bookCompleted21 = false;
  bookCompleted22 = false;
  bookCompleted23 = false;
  bookCompleted24 = false;
  bookCompleted25 = false;
  bookCompleted26 = false;
  bookCompleted27 = false;
  bookCompleted28 = false;
  bookCompleted29 = false;
  bookCompleted30 = false;

  button1 = false;
  button2 = false;
  button3 = false;
  button4 = false;
  button5 = false;
  button6 = false;
  button7 = false;
  button8 = false;
  button9 = false;
  button10 = false;
  button11 = false;
  button12 = false;
  button13 = false;
  button14 = false;
  button15 = false;
  button16 = false;
  button17 = false;
  button18 = false;
  button19 = false;
  button20 = false;
  button21 = false;
  button22 = false;
  button23 = false;
  button24 = false;
  button25 = false;
  button26 = false;
  button27 = false;
  button28 = false;
  button29 = false;
  button30 = false;

  @ViewChild('mylist') mylist: IonList;
  navCtrl: any;
  destination: any;
  try: any;
  id: number;

  constructor(
    private storageService: StorageService,
    private plt: Platform,
    private toastController: ToastController,
    public alertCtrl: AlertController
  ) {
    this.oldUser = this.storageService.getDestn();
    this.username = this.oldUser.username;
    this.email = this.oldUser.email;
    this.image = this.oldUser.ava;
  }

  gotoFinalView(destn) {
    this.storageService.setDestn(destn);
  }

  logout() {
    this.username = null;
    this.email = null;
    this.image = null;
  }

  bookCompleted1() {
    this.storageService.addUser(this.oldUser).then(() => {
      this.bookCompletedV1 = true;
      this.id = 1;
      this.oldUser.book = this.id;
      this.loadUser();
    });
    console.log(this.users);
  }

  loadUser() {
    this.storageService.getUsers().then(users => {
      this.users = users;
    });
  }

  openButton1() {
    this.button1 = true;
    this.button2 = false;
    this.button3 = false;
    this.button4 = false;
    this.button5 = false;
    this.button6 = false;
    this.button7 = false;
    this.button8 = false;
    this.button9 = false;
    this.button10 = false;
    this.button11 = false;
    this.button12 = false;
    this.button13 = false;
    this.button14 = false;
    this.button15 = false;
    this.button16 = false;
    this.button17 = false;
    this.button18 = false;
    this.button19 = false;
    this.button20 = false;
    this.button21 = false;
    this.button22 = false;
    this.button23 = false;
    this.button24 = false;
    this.button25 = false;
    this.button26 = false;
    this.button27 = false;
    this.button28 = false;
    this.button29 = false;
    this.button30 = false;
    // this.oldUser.book = this.bookCompleted1;

    // this.gotoFinalView(this.oldUser.book);
    // console.log(this.int);
    // this.bookCompleted1 = 1;
    // this.storageService.getUsers().then(data => {

    //   this.bookCompleted1 = data.find(x => x.book === 1).book;
    // //   this.bookCompleted1 = 1;
    // });
  }
  openButton2() {
    this.button1 = false;
    this.button2 = true;
    this.button3 = false;
    this.button4 = false;
    this.button5 = false;
    this.button6 = false;
    this.button7 = false;
    this.button8 = false;
    this.button9 = false;
    this.button10 = false;
    this.button11 = false;
    this.button12 = false;
    this.button13 = false;
    this.button14 = false;
    this.button15 = false;
    this.button16 = false;
    this.button17 = false;
    this.button18 = false;
    this.button19 = false;
    this.button20 = false;
    this.button21 = false;
    this.button22 = false;
    this.button23 = false;
    this.button24 = false;
    this.button25 = false;
    this.button26 = false;
    this.button27 = false;
    this.button28 = false;
    this.button29 = false;
    this.button30 = false;
  }
  openButton3() {
    this.button1 = false;
    this.button2 = false;
    this.button3 = true;
    this.button4 = false;
    this.button5 = false;
    this.button6 = false;
    this.button7 = false;
    this.button8 = false;
    this.button9 = false;
    this.button10 = false;
    this.button11 = false;
    this.button12 = false;
    this.button13 = false;
    this.button14 = false;
    this.button15 = false;
    this.button16 = false;
    this.button17 = false;
    this.button18 = false;
    this.button19 = false;
    this.button20 = false;
    this.button21 = false;
    this.button22 = false;
    this.button23 = false;
    this.button24 = false;
    this.button25 = false;
    this.button26 = false;
    this.button27 = false;
    this.button28 = false;
    this.button29 = false;
    this.button30 = false;
  }
  openButton4() {
    this.button1 = false;
    this.button2 = false;
    this.button3 = false;
    this.button4 = true;
    this.button5 = false;
    this.button6 = false;
    this.button7 = false;
    this.button8 = false;
    this.button9 = false;
    this.button10 = false;
    this.button11 = false;
    this.button12 = false;
    this.button13 = false;
    this.button14 = false;
    this.button15 = false;
    this.button16 = false;
    this.button17 = false;
    this.button18 = false;
    this.button19 = false;
    this.button20 = false;
    this.button21 = false;
    this.button22 = false;
    this.button23 = false;
    this.button24 = false;
    this.button25 = false;
    this.button26 = false;
    this.button27 = false;
    this.button28 = false;
    this.button29 = false;
    this.button30 = false;
  }
  openButton5() {
    this.button1 = false;
    this.button2 = false;
    this.button3 = false;
    this.button4 = false;
    this.button5 = true;
    this.button6 = false;
    this.button7 = false;
    this.button8 = false;
    this.button9 = false;
    this.button10 = false;
    this.button11 = false;
    this.button12 = false;
    this.button13 = false;
    this.button14 = false;
    this.button15 = false;
    this.button16 = false;
    this.button17 = false;
    this.button18 = false;
    this.button19 = false;
    this.button20 = false;
    this.button21 = false;
    this.button22 = false;
    this.button23 = false;
    this.button24 = false;
    this.button25 = false;
    this.button26 = false;
    this.button27 = false;
    this.button28 = false;
    this.button29 = false;
    this.button30 = false;
  }
  openButton6() {
    this.button1 = false;
    this.button2 = false;
    this.button3 = false;
    this.button4 = false;
    this.button5 = false;
    this.button6 = true;
    this.button7 = false;
    this.button8 = false;
    this.button9 = false;
    this.button10 = false;
    this.button11 = false;
    this.button12 = false;
    this.button13 = false;
    this.button14 = false;
    this.button15 = false;
    this.button16 = false;
    this.button17 = false;
    this.button18 = false;
    this.button19 = false;
    this.button20 = false;
    this.button21 = false;
    this.button22 = false;
    this.button23 = false;
    this.button24 = false;
    this.button25 = false;
    this.button26 = false;
    this.button27 = false;
    this.button28 = false;
    this.button29 = false;
    this.button30 = false;
  }
  openButton7() {
    this.button1 = false;
    this.button2 = false;
    this.button3 = false;
    this.button4 = false;
    this.button5 = false;
    this.button6 = false;
    this.button7 = true;
    this.button8 = false;
    this.button9 = false;
    this.button10 = false;
    this.button11 = false;
    this.button12 = false;
    this.button13 = false;
    this.button14 = false;
    this.button15 = false;
    this.button16 = false;
    this.button17 = false;
    this.button18 = false;
    this.button19 = false;
    this.button20 = false;
    this.button21 = false;
    this.button22 = false;
    this.button23 = false;
    this.button24 = false;
    this.button25 = false;
    this.button26 = false;
    this.button27 = false;
    this.button28 = false;
    this.button29 = false;
    this.button30 = false;
  }
  openButton8() {
    this.button1 = false;
    this.button2 = false;
    this.button3 = false;
    this.button4 = false;
    this.button5 = false;
    this.button6 = false;
    this.button7 = false;
    this.button8 = true;
    this.button9 = false;
    this.button10 = false;
    this.button11 = false;
    this.button12 = false;
    this.button13 = false;
    this.button14 = false;
    this.button15 = false;
    this.button16 = false;
    this.button17 = false;
    this.button18 = false;
    this.button19 = false;
    this.button20 = false;
    this.button21 = false;
    this.button22 = false;
    this.button23 = false;
    this.button24 = false;
    this.button25 = false;
    this.button26 = false;
    this.button27 = false;
    this.button28 = false;
    this.button29 = false;
    this.button30 = false;
  }
  openButton9() {
    this.button1 = false;
    this.button2 = false;
    this.button3 = false;
    this.button4 = false;
    this.button5 = false;
    this.button6 = false;
    this.button7 = false;
    this.button8 = false;
    this.button9 = true;
    this.button10 = false;
    this.button11 = false;
    this.button12 = false;
    this.button13 = false;
    this.button14 = false;
    this.button15 = false;
    this.button16 = false;
    this.button17 = false;
    this.button18 = false;
    this.button19 = false;
    this.button20 = false;
    this.button21 = false;
    this.button22 = false;
    this.button23 = false;
    this.button24 = false;
    this.button25 = false;
    this.button26 = false;
    this.button27 = false;
    this.button28 = false;
    this.button29 = false;
    this.button30 = false;
  }
  openButton10() {
    this.button1 = false;
    this.button2 = false;
    this.button3 = false;
    this.button4 = false;
    this.button5 = false;
    this.button6 = false;
    this.button7 = false;
    this.button8 = false;
    this.button9 = false;
    this.button10 = true;
    this.button11 = false;
    this.button12 = false;
    this.button13 = false;
    this.button14 = false;
    this.button15 = false;
    this.button16 = false;
    this.button17 = false;
    this.button18 = false;
    this.button19 = false;
    this.button20 = false;
    this.button21 = false;
    this.button22 = false;
    this.button23 = false;
    this.button24 = false;
    this.button25 = false;
    this.button26 = false;
    this.button27 = false;
    this.button28 = false;
    this.button29 = false;
    this.button30 = false;
  }
  openButton11() {
    this.button1 = false;
    this.button2 = false;
    this.button3 = false;
    this.button4 = false;
    this.button5 = false;
    this.button6 = false;
    this.button7 = false;
    this.button8 = false;
    this.button9 = false;
    this.button10 = false;
    this.button11 = true;
    this.button12 = false;
    this.button13 = false;
    this.button14 = false;
    this.button15 = false;
    this.button16 = false;
    this.button17 = false;
    this.button18 = false;
    this.button19 = false;
    this.button20 = false;
    this.button21 = false;
    this.button22 = false;
    this.button23 = false;
    this.button24 = false;
    this.button25 = false;
    this.button26 = false;
    this.button27 = false;
    this.button28 = false;
    this.button29 = false;
    this.button30 = false;
  }
  openButton12() {
    this.button1 = false;
    this.button2 = false;
    this.button3 = false;
    this.button4 = false;
    this.button5 = false;
    this.button6 = false;
    this.button7 = false;
    this.button8 = false;
    this.button9 = false;
    this.button10 = false;
    this.button11 = false;
    this.button12 = true;
    this.button13 = false;
    this.button14 = false;
    this.button15 = false;
    this.button16 = false;
    this.button17 = false;
    this.button18 = false;
    this.button19 = false;
    this.button20 = false;
    this.button21 = false;
    this.button22 = false;
    this.button23 = false;
    this.button24 = false;
    this.button25 = false;
    this.button26 = false;
    this.button27 = false;
    this.button28 = false;
    this.button29 = false;
    this.button30 = false;
  }
  openButton13() {
    this.button1 = false;
    this.button2 = false;
    this.button3 = false;
    this.button4 = false;
    this.button5 = false;
    this.button6 = false;
    this.button7 = false;
    this.button8 = false;
    this.button9 = false;
    this.button10 = false;
    this.button11 = false;
    this.button12 = false;
    this.button13 = true;
    this.button14 = false;
    this.button15 = false;
    this.button16 = false;
    this.button17 = false;
    this.button18 = false;
    this.button19 = false;
    this.button20 = false;
    this.button21 = false;
    this.button22 = false;
    this.button23 = false;
    this.button24 = false;
    this.button25 = false;
    this.button26 = false;
    this.button27 = false;
    this.button28 = false;
    this.button29 = false;
    this.button30 = false;
  }
  openButton14() {
    this.button1 = false;
    this.button2 = false;
    this.button3 = false;
    this.button4 = false;
    this.button5 = false;
    this.button6 = false;
    this.button7 = false;
    this.button8 = false;
    this.button9 = false;
    this.button10 = false;
    this.button11 = false;
    this.button12 = false;
    this.button13 = false;
    this.button14 = true;
    this.button15 = false;
    this.button16 = false;
    this.button17 = false;
    this.button18 = false;
    this.button19 = false;
    this.button20 = false;
    this.button21 = false;
    this.button22 = false;
    this.button23 = false;
    this.button24 = false;
    this.button25 = false;
    this.button26 = false;
    this.button27 = false;
    this.button28 = false;
    this.button29 = false;
    this.button30 = false;
  }
  openButton15() {
    this.button1 = false;
    this.button2 = false;
    this.button3 = false;
    this.button4 = false;
    this.button5 = false;
    this.button6 = false;
    this.button7 = false;
    this.button8 = false;
    this.button9 = false;
    this.button10 = false;
    this.button11 = false;
    this.button12 = false;
    this.button13 = false;
    this.button14 = false;
    this.button15 = true;
    this.button16 = false;
    this.button17 = false;
    this.button18 = false;
    this.button19 = false;
    this.button20 = false;
    this.button21 = false;
    this.button22 = false;
    this.button23 = false;
    this.button24 = false;
    this.button25 = false;
    this.button26 = false;
    this.button27 = false;
    this.button28 = false;
    this.button29 = false;
    this.button30 = false;
  }
  openButton16() {
    this.button1 = false;
    this.button2 = false;
    this.button3 = false;
    this.button4 = false;
    this.button5 = false;
    this.button6 = false;
    this.button7 = false;
    this.button8 = false;
    this.button9 = false;
    this.button10 = false;
    this.button11 = false;
    this.button12 = false;
    this.button13 = false;
    this.button14 = false;
    this.button15 = false;
    this.button16 = true;
    this.button17 = false;
    this.button18 = false;
    this.button19 = false;
    this.button20 = false;
    this.button21 = false;
    this.button22 = false;
    this.button23 = false;
    this.button24 = false;
    this.button25 = false;
    this.button26 = false;
    this.button27 = false;
    this.button28 = false;
    this.button29 = false;
    this.button30 = false;
  }
  openButton17() {
    this.button1 = false;
    this.button2 = false;
    this.button3 = false;
    this.button4 = false;
    this.button5 = false;
    this.button6 = false;
    this.button7 = false;
    this.button8 = false;
    this.button9 = false;
    this.button10 = false;
    this.button11 = false;
    this.button12 = false;
    this.button13 = false;
    this.button14 = false;
    this.button15 = false;
    this.button16 = false;
    this.button17 = true;
    this.button18 = false;
    this.button19 = false;
    this.button20 = false;
    this.button21 = false;
    this.button22 = false;
    this.button23 = false;
    this.button24 = false;
    this.button25 = false;
    this.button26 = false;
    this.button27 = false;
    this.button28 = false;
    this.button29 = false;
    this.button30 = false;
  }
  openButton18() {
    this.button1 = false;
    this.button2 = false;
    this.button3 = false;
    this.button4 = false;
    this.button5 = false;
    this.button6 = false;
    this.button7 = false;
    this.button8 = false;
    this.button9 = false;
    this.button10 = false;
    this.button11 = false;
    this.button12 = false;
    this.button13 = false;
    this.button14 = false;
    this.button15 = false;
    this.button16 = false;
    this.button17 = false;
    this.button18 = true;
    this.button19 = false;
    this.button20 = false;
    this.button21 = false;
    this.button22 = false;
    this.button23 = false;
    this.button24 = false;
    this.button25 = false;
    this.button26 = false;
    this.button27 = false;
    this.button28 = false;
    this.button29 = false;
    this.button30 = false;
  }
  openButton19() {
    this.button1 = false;
    this.button2 = false;
    this.button3 = false;
    this.button4 = false;
    this.button5 = false;
    this.button6 = false;
    this.button7 = false;
    this.button8 = false;
    this.button9 = false;
    this.button10 = false;
    this.button11 = false;
    this.button12 = false;
    this.button13 = false;
    this.button14 = false;
    this.button15 = false;
    this.button16 = false;
    this.button17 = false;
    this.button18 = false;
    this.button19 = true;
    this.button20 = false;
    this.button21 = false;
    this.button22 = false;
    this.button23 = false;
    this.button24 = false;
    this.button25 = false;
    this.button26 = false;
    this.button27 = false;
    this.button28 = false;
    this.button29 = false;
    this.button30 = false;
  }
  openButton20() {
    this.button1 = false;
    this.button2 = false;
    this.button3 = false;
    this.button4 = false;
    this.button5 = false;
    this.button6 = false;
    this.button7 = false;
    this.button8 = false;
    this.button9 = false;
    this.button10 = false;
    this.button11 = false;
    this.button12 = false;
    this.button13 = false;
    this.button14 = false;
    this.button15 = false;
    this.button16 = false;
    this.button17 = false;
    this.button18 = false;
    this.button19 = false;
    this.button20 = true;
    this.button21 = false;
    this.button22 = false;
    this.button23 = false;
    this.button24 = false;
    this.button25 = false;
    this.button26 = false;
    this.button27 = false;
    this.button28 = false;
    this.button29 = false;
    this.button30 = false;
  }
  openButton21() {
    this.button1 = false;
    this.button2 = false;
    this.button3 = false;
    this.button4 = false;
    this.button5 = false;
    this.button6 = false;
    this.button7 = false;
    this.button8 = false;
    this.button9 = false;
    this.button10 = false;
    this.button11 = false;
    this.button12 = false;
    this.button13 = false;
    this.button14 = false;
    this.button15 = false;
    this.button16 = false;
    this.button17 = false;
    this.button18 = false;
    this.button19 = false;
    this.button20 = false;
    this.button21 = true;
    this.button22 = false;
    this.button23 = false;
    this.button24 = false;
    this.button25 = false;
    this.button26 = false;
    this.button27 = false;
    this.button28 = false;
    this.button29 = false;
    this.button30 = false;
  }
  openButton22() {
    this.button1 = false;
    this.button2 = false;
    this.button3 = false;
    this.button4 = false;
    this.button5 = false;
    this.button6 = false;
    this.button7 = false;
    this.button8 = false;
    this.button9 = false;
    this.button10 = false;
    this.button11 = false;
    this.button12 = false;
    this.button13 = false;
    this.button14 = false;
    this.button15 = false;
    this.button16 = false;
    this.button17 = false;
    this.button18 = false;
    this.button19 = false;
    this.button20 = false;
    this.button21 = false;
    this.button22 = true;
    this.button23 = false;
    this.button24 = false;
    this.button25 = false;
    this.button26 = false;
    this.button27 = false;
    this.button28 = false;
    this.button29 = false;
    this.button30 = false;
  }
  openButton23() {
    this.button1 = false;
    this.button2 = false;
    this.button3 = false;
    this.button4 = false;
    this.button5 = false;
    this.button6 = false;
    this.button7 = false;
    this.button8 = false;
    this.button9 = false;
    this.button10 = false;
    this.button11 = false;
    this.button12 = false;
    this.button13 = false;
    this.button14 = false;
    this.button15 = false;
    this.button16 = false;
    this.button17 = false;
    this.button18 = false;
    this.button19 = false;
    this.button20 = false;
    this.button21 = false;
    this.button22 = false;
    this.button23 = true;
    this.button24 = false;
    this.button25 = false;
    this.button26 = false;
    this.button27 = false;
    this.button28 = false;
    this.button29 = false;
    this.button30 = false;
  }
  openButton24() {
    this.button1 = false;
    this.button2 = false;
    this.button3 = false;
    this.button4 = false;
    this.button5 = false;
    this.button6 = false;
    this.button7 = false;
    this.button8 = false;
    this.button9 = false;
    this.button10 = false;
    this.button11 = false;
    this.button12 = false;
    this.button13 = false;
    this.button14 = false;
    this.button15 = false;
    this.button16 = false;
    this.button17 = false;
    this.button18 = false;
    this.button19 = false;
    this.button20 = false;
    this.button21 = false;
    this.button22 = false;
    this.button23 = false;
    this.button24 = true;
    this.button25 = false;
    this.button26 = false;
    this.button27 = false;
    this.button28 = false;
    this.button29 = false;
    this.button30 = false;
  }
  openButton25() {
    this.button1 = false;
    this.button2 = false;
    this.button3 = false;
    this.button4 = false;
    this.button5 = false;
    this.button6 = false;
    this.button7 = false;
    this.button8 = false;
    this.button9 = false;
    this.button10 = false;
    this.button11 = false;
    this.button12 = false;
    this.button13 = false;
    this.button14 = false;
    this.button15 = false;
    this.button16 = false;
    this.button17 = false;
    this.button18 = false;
    this.button19 = false;
    this.button20 = false;
    this.button21 = false;
    this.button22 = false;
    this.button23 = false;
    this.button24 = false;
    this.button25 = true;
    this.button26 = false;
    this.button27 = false;
    this.button28 = false;
    this.button29 = false;
    this.button30 = false;
  }
  openButton26() {
    this.button1 = false;
    this.button2 = false;
    this.button3 = false;
    this.button4 = false;
    this.button5 = false;
    this.button6 = false;
    this.button7 = false;
    this.button8 = false;
    this.button9 = false;
    this.button10 = false;
    this.button11 = false;
    this.button12 = false;
    this.button13 = false;
    this.button14 = false;
    this.button15 = false;
    this.button16 = false;
    this.button17 = false;
    this.button18 = false;
    this.button19 = false;
    this.button20 = false;
    this.button21 = false;
    this.button22 = false;
    this.button23 = false;
    this.button24 = false;
    this.button25 = false;
    this.button26 = true;
    this.button27 = false;
    this.button28 = false;
    this.button29 = false;
    this.button30 = false;
  }
  openButton27() {
    this.button1 = false;
    this.button2 = false;
    this.button3 = false;
    this.button4 = false;
    this.button5 = false;
    this.button6 = false;
    this.button7 = false;
    this.button8 = false;
    this.button9 = false;
    this.button10 = false;
    this.button11 = false;
    this.button12 = false;
    this.button13 = false;
    this.button14 = false;
    this.button15 = false;
    this.button16 = false;
    this.button17 = false;
    this.button18 = false;
    this.button19 = false;
    this.button20 = false;
    this.button21 = false;
    this.button22 = false;
    this.button23 = false;
    this.button24 = false;
    this.button25 = false;
    this.button26 = false;
    this.button27 = true;
    this.button28 = false;
    this.button29 = false;
    this.button30 = false;
  }
  openButton28() {
    this.button1 = false;
    this.button2 = false;
    this.button3 = false;
    this.button4 = false;
    this.button5 = false;
    this.button6 = false;
    this.button7 = false;
    this.button8 = false;
    this.button9 = false;
    this.button10 = false;
    this.button11 = false;
    this.button12 = false;
    this.button13 = false;
    this.button14 = false;
    this.button15 = false;
    this.button16 = false;
    this.button17 = false;
    this.button18 = false;
    this.button19 = false;
    this.button20 = false;
    this.button21 = false;
    this.button22 = false;
    this.button23 = false;
    this.button24 = false;
    this.button25 = false;
    this.button26 = false;
    this.button27 = false;
    this.button28 = true;
    this.button29 = false;
    this.button30 = false;
  }
  openButton29() {
    this.button1 = false;
    this.button2 = false;
    this.button3 = false;
    this.button4 = false;
    this.button5 = false;
    this.button6 = false;
    this.button7 = false;
    this.button8 = false;
    this.button9 = false;
    this.button10 = false;
    this.button11 = false;
    this.button12 = false;
    this.button13 = false;
    this.button14 = false;
    this.button15 = false;
    this.button16 = false;
    this.button17 = false;
    this.button18 = false;
    this.button19 = false;
    this.button20 = false;
    this.button21 = false;
    this.button22 = false;
    this.button23 = false;
    this.button24 = false;
    this.button25 = false;
    this.button26 = false;
    this.button27 = false;
    this.button28 = false;
    this.button29 = true;
    this.button30 = false;
  }
  openButton30() {
    this.button1 = false;
    this.button2 = false;
    this.button3 = false;
    this.button4 = false;
    this.button5 = false;
    this.button6 = false;
    this.button7 = false;
    this.button8 = false;
    this.button9 = false;
    this.button10 = false;
    this.button11 = false;
    this.button12 = false;
    this.button13 = false;
    this.button14 = false;
    this.button15 = false;
    this.button16 = false;
    this.button17 = false;
    this.button18 = false;
    this.button19 = false;
    this.button20 = false;
    this.button21 = false;
    this.button22 = false;
    this.button23 = false;
    this.button24 = false;
    this.button25 = false;
    this.button26 = false;
    this.button27 = false;
    this.button28 = false;
    this.button29 = false;
    this.button30 = true;
  }
}
